version: '3'

services:
    web:
        image: nginx:1.13-alpine
        container_name: rnq-web
        network_mode: host
        ports:
            - 80:80
        volumes:
            - ./../app:/srv/app
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    php:
        build: ./php
        image: rnq-php
        container_name: rnq-php
        network_mode: host
        volumes:
            - ./../app:/srv/app

    worker:
        build: ./worker
        image: rnq-worker
        container_name: rnq-worker
        network_mode: host
        volumes:
            - ./../app:/srv/app
        depends_on:
            - rabbitmq

    db:
        build: ./db
        image: rnq-db
        container_name: rnq-db
        network_mode: host
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: rnq-db
            MYSQL_USER: rnq-db
            MYSQL_PASSWORD: rnq-db
        ports:
            - 3306:3306
        volumes:
            - ./../tmp/db:/var/lib/mysql

    rabbitmq:
        image: rabbitmq:3.7-management-alpine
        container_name: rnq-rabbitmq
        network_mode: host